accounts/urls.py
from django.conf import urls
try:
    from django.core import urlresolvers
    carret = '^'
except ImportError:
    from django import urls as urlresolvers
    carret = ''
from django.contrib.auth import views as auth_views, decorators

from accounts import views as accounts_views, forms
from accounts.conf import settings


app_name = 'accounts'
base_template = settings['base_template']

urlpatterns = [
    urls.url(
        r'{}login/$'.format(carret),
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            authentication_form=forms.AuthenticationForm,
            extra_context={
                'base_template': base_template
            }
        ),
        name='login'
    ),
    urls.url(
        r'{}logout/$'.format(carret),
        auth_views.LogoutView.as_view(
            template_name='accounts/logout.html',
            extra_context={
                'base_template': base_template
            }
        ),
        name='logout'
    ),
    urls.url(
        r'{}password_change/$'.format(carret),
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/password_change_form.html',
            success_url=(
                urlresolvers.reverse_lazy('accounts:password_change_done')
            ),
            extra_context={
                'base_template': base_template
            }
        ),
        name='password_change'
    ),
    urls.url(
        r'{}password_change/done/$'.format(carret),
        auth_views.PasswordChangeDoneView.as_view(
            template_name='accounts/password_change_done.html',
            extra_context={
                'base_template': base_template
            }
        ),
        name='password_change_done'
    ),
    urls.url(
        r'{}password_reset/$'.format(carret),
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset_form.html',
            email_template_name='accounts/password_reset_email.html',
            success_url=(
                urlresolvers.reverse_lazy('accounts:password_reset_done')
            ),
            extra_context={
                'base_template': base_template
            }
        ),
        name='password_reset'
    ),
    urls.url(
        r'{}password_reset/done/$'.format(carret),
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html',
            extra_context={
                'base_template': base_template
            }
        ),
        name='password_reset_done'),
    urls.url(
        r'{}reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'.format(carret) +
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=(
                urlresolvers.reverse_lazy('accounts:password_reset_complete')
            ),
            extra_context={
                'base_template': base_template
            }
        ),
        name='password_reset_confirm'),
    urls.url(
        r'{}reset/done/$'.format(carret),
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html',
            extra_context={
                'base_template': base_template
            }
        ),
        name='password_reset_complete'
    ),
    urls.url(
        r'{}(?P<pk>\d+)/$'.format(carret),
        decorators.login_required(accounts_views.UserDetail.as_view()),
        name='user_detail'
    ),
    urls.url(
        r'{}create/$'.format(carret),
        accounts_views.UserCreate.as_view(),
        name='user_create'
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model

from accounts.conf import settings


User = get_user_model()


class AuthenticationForm(auth_forms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['autofocus'] = True


class UserCreationForm(auth_forms.UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2',
        ) + settings['user_create_fields']

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        user_create_required_fields = settings['user_create_required_fields']
        if user_create_required_fields:
            for field in self.fields:
                if field in user_create_required_fields:
                    self.fields[field].required = True

accounts/views.py
from django import shortcuts
from django.views import generic
from django.contrib import auth
from django.contrib.auth import get_user_model

from accounts.conf import settings
from accounts import forms


base_template = settings['base_template']


User = get_user_model()


class UserDetail(generic.DetailView):
    model = User
    template_name = "accounts/user_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['base_template'] = base_template

        return context


class UserCreate(generic.CreateView):
    model = User
    form_class = forms.UserCreationForm
    template_name = 'accounts/user_create.html'
    success_url = settings['user_create_success_url']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['base_template'] = base_template

        return context

    def form_valid(self, form):
        self.object = form.save()
        user = auth.authenticate(
            email=self.object.email, password=form.cleaned_data['password1']
        )
        auth.login(self.request, user)
        return shortcuts.redirect(self.success_url)

accounts/templates/accounts/login.html
{% extends base_template %}

{% load crispy_forms_tags %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">Log in</h3>
        </div>
        <div class="panel-body">
            {% if form.errors %}
                <p>
                    Your username and password didn't match. Please try again.
                </p>
            {% endif %}

            {% if next %}
                {% if user.is_authenticated %}
                    <p>
                        Your account doesn't have access to this page. To proceed, please log in with an account that has access.
                    </p>
                {% else %}
                    <p>
                        Please log in to see this page.
                    </p>
                {% endif %}
            {% endif %}

            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-4">
                        {{ form|crispy }}
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-log-in"
                            aria-hidden="true"
                            ></span>
                        Log in
                    </button>
                </div>
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
        <div class="panel-footer">
            {# Assumes you setup the password_reset view in your URLconf #}
            <a href="{% url 'accounts:password_reset' %}"
                class="btn btn-default"
                >
                <span class="glyphicon glyphicon-question-sign"
                    aria-hidden="true"
                    ></span>
                Lost password?
            </a>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends base_template %}

{% load i18n %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">Logged out</h3>
        </div>
        <div class="panel-body">
            <p>
                {% trans "Thanks for spending some quality time with the Web site today." %}
            </p>

            <p>
                <a href="{% url 'accounts:login' %}" class="btn btn-default">
                    <span class="glyphicon glyphicon-log-in"
                        aria-hidden="true"
                        ></span>
                    {% trans 'Log in again' %}
                </a>
            </p>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends base_template %}

{% load i18n %}

{% block title %} - {{ title }}{% endblock title %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <p>
                {% trans 'Your password was changed.' %}
            </p>
            <p>
                <a href="/" class="btn btn-default">
                    <span class="glyphicon glyphicon-globe"
                        aria-hidden="true"
                        ></span>
                    {% trans 'Done' %}
                </a>
            </p>
        </div>
    </div>

{% endblock content%}

accounts/templates/accounts/password_change_form.html
{% extends base_template %}

{% load i18n static %}
{% load crispy_forms_tags %}

{% block title %} - {{ title }}{% endblock %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <p class="text-danger">
                        {% if form.errors.items|length == 1 %}
                            {% trans "Please correct the error below." %}
                        {% else %}
                            {% trans "Please correct the errors below." %}
                        {% endif %}
                    </p>
                {% endif %}

                <p>
                    {% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}
                </p>

                <fieldset>
                    <div class="row">
                        <div class="col-lg-4">
                            {{ form|crispy }}
                        </div>
                    </div>
                </fieldset>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-pencil"
                            aria-hidden="true"
                            ></span>
                        {% trans 'Change my password' %}
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends base_template %}

{% load i18n %}

{% block title %} - {{ title }}{% endblock %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <p>
                {% trans "Your password has been set.  You may go ahead and log in now." %}
            </p>

            <p>
                <a href="{{ login_url }}" class="btn btn-default">
                    <span class="glyphicon glyphicon-log-in"
                        aria-hidden="true"
                        ></span>
                    {% trans 'Log in' %}
                </a>
            </p>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends base_template %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %} - {{ title }}{% endblock %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            {% if validlink %}
                <p>
                    {% trans "Please enter your new password twice so we can verify you typed it in correctly." %}
                </p>

                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-4">
                            {{ form|crispy }}
                        </div>
                    </div>
                    <p>
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-pencil"
                                aria-hidden="true"
                                ></span>
                            {% trans 'Change my password' %}
                        </button>
                    </p>
                </form>
            {% else %}
                <p>
                    {% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}
                </p>
            {% endif %}
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends base_template %}

{% load i18n %}

{% block title %} - {{ title }}{% endblock %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <p>
                {% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}
            </p>

            <p>
                {% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}
            </p>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{# gross format here has nice output in email #}{% load i18n %}{% autoescape off %}{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
    {% if 'https://' not in domain and 'http://' not in domain %}{{ protocol }}://{% endif %}{% if domain|last == '/' %}{{ domain|slice:":-1" }}{% else %}{{ domain }}{% endif %}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}--
The {{ site_name }} team{% endblocktrans %}{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends base_template %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %} - {{ title }}{% endblock %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <p>
                {% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}
            </p>

            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-4">
                        {{ form|crispy }}
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-pencil"
                            aria-hidden="true"
                            ></span>
                        {% trans 'Reset my password' %}
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/user_create.html
{% extends base_template %}

{% load crispy_forms_tags %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">Sign up</h3>
        </div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-4">
                        {{ form|crispy }}
                    </div>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-log-in"
                            aria-hidden="true"
                            ></span>
                        Sign up
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends base_template %}

{% block content %}

    {% include 'utils/messages.html' %}
    <div class="panel panel-default" style="margin-top: 20px;">
        <div class="panel-heading">
            <h3 class="panel-title">User</h3>
        </div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                {% if object.get_username != object.email %}
                    <dt>Username:</dt>
                    <dd>{{ object.get_username }}</dd>
                {% endif %}
                <dt>Email:</dt>
                <dd>{{ object.email }}</dd>
                <dt>Full name:</dt>
                <dd>{{ object.get_full_name }}</dd>
                <dt>Last login:</dt>
                <dd>{{ object.last_login }}</dd>
                <dt>Date joined:</dt>
                <dd>{{ object.date_joined }}</dd>
            </dl>
        </div>
        <div class="panel-footer">
            <a href="{% url 'accounts:password_change' %}"
                class="btn btn-default"
                >
                <span class="glyphicon glyphicon-pencil"
                    aria-hidden="true"
                    ></span>
                Change password
            </a>
        </div>
    </div>

{% endblock %}

accounts/templates/utils/messages.html
{% load bootstrap_tags %}

{% for message in messages %}
    <div class="alert{{ message.tags|bootstrap_tags }}">
        <button type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
            >
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}